# Generated by Django 5.0 on 2023-12-09 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfie_registration', '0002_alter_userselfie_selfie_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userselfie',
            name='selfie_embedding',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
