# Generated by Django 5.0 on 2023-12-11 06:43

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('uploaded_by', models.CharField(max_length=255)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('album_cover', models.ImageField(upload_to='upload/album_covers/')),
            ],
        ),
        migrations.CreateModel(
            name='CroppedFace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='upload/cropped_faces/')),
                ('face_locations', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('face_embedding', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cropped_faces', to='photographers.album')),
            ],
        ),
    ]
