# Generated by Django 5.0 on 2023-12-11 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photographers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='croppedface',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photographers.album'),
        ),
        migrations.AlterField(
            model_name='croppedface',
            name='face_embedding',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='croppedface',
            name='face_locations',
            field=models.JSONField(),
        ),
    ]
